### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Hexaae** [spoonieau/PlayLeft#1]
Please, send me the text strings. I'll add Italian language support.

Can you also release a cheap paid version without Ads?

**Comment by spoonieau** [comment]
Hey Hexaae 
For sure that will be great if your interested. Hopefully going to get some time over the week end to set up localization support. 
Never thought of releasing a paid version, it was all just a test to see how the windows store/ UWP apps worked.

**Comment by spoonieau** [comment]
I have had Italian language support 1.3V, by using Google Translate. Localization is in Strings/it_IT/Resources.resw
